# Generated by Django 5.0.6 on 2026-09-17 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='date de début')),
                ('date_end', models.DateField(verbose_name='date de fin')),
                ('is_available', models.BooleanField(default=True, help_text="Décocher pour marquer une période d'indisponibilité.", verbose_name='disponible')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.painterprofile', verbose_name='peintre')),
            ],
            options={
                'verbose_name': 'disponibilité',
                'verbose_name_plural': 'disponibilités',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(blank=True, max_length=300, verbose_name='texte de recherche')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('results_count', models.PositiveSmallIntegerField(default=0, verbose_name='nombre de résultats')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory', verbose_name='catégorie recherchée')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'log de recherche',
                'verbose_name_plural': 'logs de recherche',
                'ordering': ['-timestamp'],
            },
        ),
    ]
