# Generated by Django 5.0.6 on 2026-09-25 22:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('QUOTE_REQUEST', 'Nouvelle demande de devis'), ('QUOTE_SENT', 'Devis reçu'), ('QUOTE_ACCEPTED', 'Devis accepté'), ('QUOTE_REFUSED', 'Devis refusé'), ('BOOKING', 'Réservation'), ('WORK_PROGRESS', 'Avancement travaux'), ('WORK_FINISHED', 'Travaux terminés'), ('NEW_REVIEW', 'Nouvelle évaluation'), ('PROFILE', 'Profil'), ('MESSAGE', 'Nouveau message')], default='MESSAGE', max_length=30, verbose_name='type')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='lu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
