# Generated by Django 5.0.6 on 2026-09-17 22:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: paint-bucket)", max_length=50, verbose_name='icône')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name="ordre d'affichage")),
            ],
            options={
                'verbose_name': 'catégorie de prestation',
                'verbose_name_plural': 'catégories de prestations',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='lieu')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='date de réalisation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='accounts.painterprofile', verbose_name='peintre')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='services.servicecategory', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'réalisation',
                'verbose_name_plural': 'réalisations',
                'ordering': ['-date_completed', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='portfolio/%Y/%m/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('is_cover', models.BooleanField(default=False, verbose_name='image principale')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.portfolio', verbose_name='réalisation')),
            ],
            options={
                'verbose_name': 'image de réalisation',
                'verbose_name_plural': 'images de réalisation',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('RCCM', 'RCCM / Registre de commerce'), ('DIPLOME', 'Diplôme'), ('CERTIF', 'Certification'), ('ASSURANCE', "Attestation d'assurance"), ('AUTRE', 'Autre document')], default='AUTRE', max_length=20, verbose_name='type de document')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('file', models.FileField(upload_to='professional_docs/%Y/%m/', verbose_name='fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifié par admin')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_docs', to='accounts.painterprofile', verbose_name='peintre')),
            ],
            options={
                'verbose_name': 'document professionnel',
                'verbose_name_plural': 'documents professionnels',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='intitulé')),
                ('issuing_body', models.CharField(blank=True, max_length=200, verbose_name='organisme émetteur')),
                ('date_obtained', models.DateField(blank=True, null=True, verbose_name="date d'obtention")),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='accounts.painterprofile', verbose_name='peintre')),
            ],
            options={
                'verbose_name': 'qualification',
                'verbose_name_plural': 'qualifications',
                'ordering': ['-date_obtained'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price_range_min', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix minimum (FCFA/m²)')),
                ('price_range_max', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix maximum (FCFA/m²)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offers', to='services.servicecategory', verbose_name='catégorie')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offers', to='accounts.painterprofile', verbose_name='peintre')),
            ],
            options={
                'verbose_name': 'offre de service',
                'verbose_name_plural': 'offres de services',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='services.servicecategory', verbose_name='catégorie')),
            ],
            options={
                'verbose_name': 'compétence',
                'verbose_name_plural': 'compétences',
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PainterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUTANT', 'Débutant'), ('CONFIRME', 'Confirmé'), ('EXPERT', 'Expert')], default='CONFIRME', max_length=20, verbose_name='niveau')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painter_skills', to='accounts.painterprofile', verbose_name='peintre')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='painter_skills', to='services.skill', verbose_name='compétence')),
            ],
            options={
                'verbose_name': 'compétence du peintre',
                'verbose_name_plural': 'compétences du peintre',
                'unique_together': {('painter', 'skill')},
            },
        ),
    ]
