# Generated by Django 5.0.6 on 2026-09-20 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Identifiant unique du paramètre (snake_case)', max_length=100, unique=True, verbose_name='clé')),
                ('value', models.TextField(help_text='Valeur du paramètre (texte, nombre ou JSON)', verbose_name='valeur')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='description')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'paramètre plateforme',
                'verbose_name_plural': 'paramètres plateforme',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('VALIDATE_PAINTER', 'Validation peintre'), ('REFUSE_PAINTER', 'Refus peintre'), ('SUSPEND_PAINTER', 'Suspension peintre'), ('REQUEST_COMPLEMENT', 'Complément demandé'), ('ACTIVATE_USER', 'Activation utilisateur'), ('DEACTIVATE_USER', 'Désactivation utilisateur'), ('DELETE_USER', 'Suppression utilisateur'), ('UPDATE_SETTINGS', 'Mise à jour paramètres'), ('OTHER', 'Autre')], default='OTHER', max_length=30, verbose_name='action')),
                ('target_model', models.CharField(blank=True, max_length=100, verbose_name='modèle cible')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='ID cible')),
                ('target_label', models.CharField(blank=True, help_text='Description lisible de la cible (ex: nom du peintre)', max_length=200, verbose_name='libellé cible')),
                ('note', models.TextField(blank=True, help_text="Note ou motif de l'action", verbose_name='note')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='horodatage')),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_logs', to=settings.AUTH_USER_MODEL, verbose_name='administrateur')),
            ],
            options={
                'verbose_name': 'journal admin',
                'verbose_name_plural': 'journal admin',
                'ordering': ['-timestamp'],
            },
        ),
    ]
