# Generated by Django 5.0.6 on 2026-09-21 17:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('intro_text', models.TextField(blank=True, verbose_name="texte d'introduction")),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant total (FCFA)')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name="valide jusqu'au")),
                ('notes', models.TextField(blank=True, verbose_name='notes et conditions')),
                ('ai_assisted', models.BooleanField(default=False, help_text="Indique si ce devis a été rédigé avec l'assistance IA.", verbose_name="assisté par l'IA")),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], db_index=True, default='BROUILLON', max_length=20, verbose_name='statut')),
                ('client_note', models.TextField(blank=True, help_text="Motif d'acceptation ou de refus du client.", verbose_name='note du client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyé le')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='accounts.painterprofile', verbose_name='peintre')),
            ],
            options={
                'verbose_name': 'devis',
                'verbose_name_plural': 'devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='date prévue')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('CONFIRME', 'Confirmée'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminée'), ('ANNULE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='accounts.painterprofile', verbose_name='peintre')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='transactions.quote', verbose_name='devis')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantité')),
                ('unit', models.CharField(default='m²', help_text='Ex : m², h, forfait, unité', max_length=30, verbose_name='unité')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix unitaire (FCFA)')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix total (FCFA)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.quote', verbose_name='devis')),
            ],
            options={
                'verbose_name': 'ligne de devis',
                'verbose_name_plural': 'lignes de devis',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='titre des travaux')),
                ('description', models.TextField(verbose_name='description détaillée')),
                ('location', models.CharField(max_length=200, verbose_name='lieu des travaux')),
                ('surface_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='surface estimée (m²)')),
                ('desired_start_date', models.DateField(blank=True, null=True, verbose_name='date souhaitée de début')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='budget maximum (FCFA)')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente de réponse'), ('REPONDU', 'Devis reçu'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory', verbose_name='catégorie de prestation')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='accounts.painterprofile', verbose_name='peintre')),
            ],
            options={
                'verbose_name': 'demande de devis',
                'verbose_name_plural': 'demandes de devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='transactions.quoterequest', verbose_name='demande de devis'),
        ),
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_label', models.CharField(max_length=200, verbose_name='étape')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('percentage', models.PositiveSmallIntegerField(default=0, help_text='0 à 100', verbose_name='avancement (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='transactions.booking', verbose_name='réservation')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='mis à jour par')),
            ],
            options={
                'verbose_name': 'étape de travaux',
                'verbose_name_plural': 'étapes de travaux',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('ACOMPTE', 'Acompte'), ('SOLDE', 'Solde')], max_length=10, verbose_name='type de paiement')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant (FCFA)')),
                ('currency', models.CharField(default='XAF', max_length=3, verbose_name='devise')),
                ('method', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('VIREMENT', 'Virement bancaire'), ('ESPECES', 'Espèces'), ('AUTRE', 'Autre')], default='MTN_MOMO', max_length=20, verbose_name='moyen de paiement')),
                ('provider', models.CharField(blank=True, help_text='Nom du fournisseur de paiement (MTN, Orange, etc.)', max_length=100, verbose_name='fournisseur')),
                ('transaction_ref', models.CharField(blank=True, max_length=200, verbose_name='référence transaction')),
                ('phone_number', models.CharField(blank=True, help_text='Numéro Mobile Money utilisé pour le paiement', max_length=20, verbose_name='numéro de téléphone')),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITE', 'Traité'), ('ECHOUE', 'Échoué'), ('REMBOURSE', 'Remboursé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.booking', verbose_name='réservation')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'payment_type')},
            },
        ),
    ]
