# Generated by Django 5.0.6 on 2026-09-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogress',
            name='photo',
            field=models.FileField(blank=True, help_text='Photo illustrant cette étape des travaux', null=True, upload_to='work_progress/%Y/%m/', verbose_name='photo'),
        ),
    ]
