# Generated by Django 5.0.6 on 2026-09-24 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_workprogress_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('photo', models.FileField(blank=True, null=True, upload_to='progress_reactions/%Y/%m/', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reactions', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='transactions.workprogress', verbose_name='étape')),
            ],
            options={
                'verbose_name': 'réaction',
                'verbose_name_plural': 'réactions',
                'ordering': ['created_at'],
            },
        ),
    ]
