# Generated by Django 5.0.6 on 2026-09-17 16:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='adresse e-mail')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='téléphone')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('address', models.TextField(blank=True, verbose_name='adresse')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/', verbose_name='photo de profil')),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('PEINTRE', 'Peintre'), ('ADMIN', 'Administrateur')], db_index=True, default='CLIENT', max_length=20, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'inscription")),
                ('email_verified', models.BooleanField(default=False, verbose_name='e-mail vérifié')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=dict, verbose_name='préférences')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil client',
                'verbose_name_plural': 'profils clients',
            },
        ),
        migrations.CreateModel(
            name='PainterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='présentation')),
                ('years_experience', models.PositiveSmallIntegerField(default=0, verbose_name="années d'expérience")),
                ('professional_id', models.CharField(blank=True, max_length=100, verbose_name='numéro professionnel')),
                ('validation_status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé'), ('SUSPENDU', 'Suspendu'), ('COMPLEMENT', 'Complément demandé')], db_index=True, default='EN_ATTENTE', max_length=20, verbose_name='statut de validation')),
                ('validation_date', models.DateTimeField(blank=True, null=True, verbose_name='date de validation')),
                ('validation_note', models.TextField(blank=True, verbose_name='note de validation / motif de refus')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='note moyenne')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name="nombre d'évaluations")),
                ('is_featured', models.BooleanField(default=False, help_text="Peintre mis en avant sur la page d'accueil.", verbose_name='mis en avant')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'PEINTRE'}, on_delete=django.db.models.deletion.CASCADE, related_name='painter_profile', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_painters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil peintre',
                'verbose_name_plural': 'profils peintres',
                'ordering': ['-average_rating', '-total_reviews'],
            },
        ),
    ]
