# Generated by Django 5.0.6 on 2026-09-24 20:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0003_progressreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Note de 1 à 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note')),
                ('comment', models.TextField(blank=True, help_text='Commentaire optionnel du client', verbose_name='commentaire')),
                ('painter_reply', models.TextField(blank=True, help_text="Réponse optionnelle du peintre à l'évaluation", verbose_name='réponse du peintre')),
                ('is_visible', models.BooleanField(default=True, help_text="L'admin peut masquer une évaluation inappropriée", verbose_name='visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='transactions.booking', verbose_name='réservation')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='client')),
                ('painter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.painterprofile', verbose_name='peintre')),
            ],
            options={
                'verbose_name': 'évaluation',
                'verbose_name_plural': 'évaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
